#NumPy Challenge

Create a NumPy ndarray object by using this list of numbers [7,8,4,5,1,2].


In [0]:
import numpy as np
arr = np.array([7,8,4,5,1,2])
print(arr)

Using slicing print the elements from index 3 to the end of the array.



In [7]:
import numpy as np
arr = np.array([7,8,4,5,1,2])

print(arr[3:])

[5 1 2]


Using slicing print all the elements except the last one.



In [0]:
import numpy as np
arr = np.array([7,8,4,5,1,2])

print(arr[:5])

[7 8 4 5 1]


Using slicing print the elements from index 1 to index 4 of the array.



In [0]:
import numpy as np
arr = np.array([7,8,4,5,1,2])

print(arr[:4])

[7 8 4 5]


Reshape the array into a 3 rows and 2 cols (3,2).



In [0]:
import numpy as np
arr = np.array([7,8,4,5,1,2])
print(arr.reshape(3, 2))

[[7 8]
 [4 5]
 [1 2]]


Print all the array elements one by one (iterating).



In [0]:
import numpy as np
arr = np.array([7,8,4,5,1,2])
for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 7
(1,) 8
(2,) 4
(3,) 5
(4,) 1
(5,) 2


Create a new NumPy ndarray object by using this list of numbers [0,6,9].



In [0]:
import numpy as np
arr = np.array([0,6,9])
print(arr)

[0 6 9]


Join the two arrays.



In [0]:
import numpy as np
arr1 = np.array([0,6,9])
arr2 = np.array([7,8,4,5,1,2])
arr = np.concatenate((arr1, arr2))             
print(arr)               


[0 6 9 7 8 4 5 1 2]


Using filtering print only the odd numbers of the joined array.



In [0]:
import numpy as np
arr1 = np.array([0,6,9])
arr2 = np.array([7,8,4,5,1,2])
arr = np.concatenate((arr1, arr2))  
odd = np.where(arr%2 != 0)   
print(odd) 
  

(array([2, 3, 6, 7]),)


Sort the joined array elements.



In [0]:
import numpy as np
arr1 = np.array([0,6,9])
arr2 = np.array([7,8,4,5,1,2])
arr = np.concatenate((arr1, arr2)) 
sort = np.sort(arr)
print(sort) 

[0 1 2 4 5 6 7 8 9]


Store in an array the names of the months.



In [0]:
import numpy as np
arr = np.array(['enero','febrero','marzo','abril','mayo','junio','julio','agosto','septiembre','octubre','noviembre','diciembre'])
print(arr)

['enero' 'febrero' 'marzo' 'abril' 'mayo' 'junio' 'julio' 'agosto'
 'septiembre' 'octubre' 'noviembre' 'diciembre']


Split the months array in 4 periods of 3 elements each one.



In [0]:
import numpy as np
arr = np.array(['enero','febrero','marzo','abril','mayo','junio','julio','agosto','septiembre','octubre','noviembre','diciembre'])
split= arr.reshape(4, 3)
print(split)

[['enero' 'febrero' 'marzo']
 ['abril' 'mayo' 'junio']
 ['julio' 'agosto' 'septiembre']
 ['octubre' 'noviembre' 'diciembre']]


Create an array with genre information ['F','M','F','F','M','F'].



In [0]:
import numpy as np
arr = np.array(['F','M','F','F','M','F'])
print(arr)

['F' 'M' 'F' 'F' 'M' 'F']


Find the indexes where the value is F.



In [0]:
import numpy as np
arr = np.array(['F','M','F','F','M','F'])
find =np.searchsorted(arr, 'F')
print(find)

0


Store in an array the age information [18,20,19,23,19,20].



In [0]:
import numpy as np
arr = np.array([18,20,19,23,19,20])
print(arr)

[18 20 19 23 19 20]


Create a filter array with values < 20.



In [0]:
import numpy as np
arr = np.array([18,20,19,23,19,20])

filter_arr = arr <20
newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[ True False  True False  True False]
[18 19 19]


Change the 3 index element with a value of 22



In [5]:
import numpy as np #0 el índice del primer elemento
arr = np.array([18,20,19,23,19,20])
change = arr.view()
change[3] = 22
print(change)

[18 20 22 23 19 20]


Print the 4 index element.

In [6]:
import numpy as np 
arr = np.array([18,20,19,23,19,20])
change = arr.view()
change[2] = 22
print(change[4])

19
